languages = {
    'Deutsch': {
        'welcome': 'Willkommen',
        'login_register': 'Login / Registrieren',
        'login': 'Login',
        'register': 'Registrieren',
        'forgot_password': 'Passwort vergessen',
        'ekg_data': 'EKG-Daten',
        'fitness_data': 'Fitnessdaten',
        'meals_sports': 'Mahlzeiten & Sport',
        'ki_features': 'KI-Funktionen',
        'db_management': 'Datenbank-Verwaltung',
        'select_person': 'Person auswählen',
        'gender': 'Geschlecht',
        'age': 'Alter',
        'data': 'Daten',
        'graph': 'Graph',
        'average_heart_rate': 'Durchschnittliche Herzfrequenz',
        'no_data': 'Keine Daten vorhanden',
        'bmi_nutrition': 'BMI & Ernährung',
        'track_meals_sports': 'Mahlzeiten & Sport verfolgen',
        'ki_description': 'Beschreibung der KI-Funktionalitäten',
        'db_management': 'Datenbank-Verwaltung',
        'user_management': 'Benutzerverwaltung',
        'show_user': 'Benutzer anzeigen',
        'clean_data': 'Daten löschen',
        'delete_all_data': 'Alle Daten löschen',
        'confirm': 'Bestätigen',
        'success_delete': 'Erfolgreich gelöscht',
        'export_data': 'Daten exportieren',
        'export_success': 'Export erfolgreich',
        'backup_restore': 'Backup & Wiederherstellung',
        'create_backup': 'Backup erstellen',
        'backup_success': 'Backup erfolgreich',
        'upload_backup': 'Backup hochladen',
        'restore_success': 'Wiederherstellung erfolgreich',
        'show_user': 'Benutzername eingeben',
        'user_not_found': 'Benutzer nicht gefunden',
        'bmi_calculate': 'BMI berechnen',
        'weight': 'Gewicht',
        'height': 'Größe',
        'bmi_is': 'Ihr BMI ist: {:.2f}',
        'bmi_status': 'BMI-Status: {}',
        'valid_height': 'Bitte geben Sie eine gültige Größe ein.',
        'daily_calorie': 'Täglicher Kalorienbedarf',
        'age': 'Alter',
        'activity_level': 'Aktivitätslevel',
        'activity_levels': ['Wenig aktiv', 'Mäßig aktiv', 'Aktiv', 'Sehr aktiv'],
        'calorie_need': 'Ihr täglicher Kalorienbedarf beträgt: {:.2f} Kalorien',
        'save_data': 'Daten speichern',
        'success_save': 'Daten erfolgreich gespeichert',
        'weight_bmi_progress': 'Gewichts- und BMI-Verlauf',
        'positive': 'Positives Feedback',
        'weight_data': 'Gewichtsdaten',
        'weight_progress': 'Gewichtsverlauf',
        'no_weight_data': 'Keine Gewichtsdaten vorhanden',
        'bmi_progress': 'BMI-Verlauf',
        'no_bmi_data': 'Keine BMI-Daten vorhanden',
        'pyramid': 'Ernährungspyramide',
        'body_positivity_quotes': 'Körperpositivität Zitate'
    },
    'English': {
        'welcome': 'Welcome',
        'login_register': 'Login / Register',
        'login': 'Login',
        'register': 'Register',
        'forgot_password': 'Forgot Password',
        'ekg_data': 'EKG Data',
        'fitness_data': 'Fitness Data',
        'meals_sports': 'Meals & Sports',
        'ki_features': 'AI Features',
        'db_management': 'Database Management',
        'select_person': 'Select Person',
        'gender': 'Gender',
        'age': 'Age',
        'data': 'Data',
        'graph': 'Graph',
        'average_heart_rate': 'Average Heart Rate',
        'no_data': 'No data available',
        'bmi_nutrition': 'BMI & Nutrition',
        'track_meals_sports': 'Track Meals & Sports',
        'ki_description': 'Description of AI functionalities',
        'db_management': 'Database Management',
        'user_management': 'User Management',
        'show_user': 'Show User',
        'clean_data': 'Clean Data',
        'delete_all_data': 'Delete All Data',
        'confirm': 'Confirm',
        'success_delete': 'Successfully deleted',
        'export_data': 'Export Data',
        'export_success': 'Export successful',
        'backup_restore': 'Backup & Restore',
        'create_backup': 'Create Backup',
        'backup_success': 'Backup successful',
        'upload_backup': 'Upload Backup',
        'restore_success': 'Restore successful',
        'show_user': 'Enter username',
        'user_not_found': 'User not found',
        'bmi_calculate': 'Calculate BMI',
        'weight': 'Weight',
        'height': 'Height',
        'bmi_is': 'Your BMI is: {:.2f}',
        'bmi_status': 'BMI Status: {}',
        'valid_height': 'Please enter a valid height.',
        'daily_calorie': 'Daily Calorie Requirement',
        'age': 'Age',
        'activity_level': 'Activity Level',
        'activity_levels': ['Not very active', 'Moderately active', 'Active', 'Very active'],
        'calorie_need': 'Your daily calorie requirement is: {:.2f} calories',
        'save_data': 'Save Data',
        'success_save': 'Data successfully saved',
        'weight_bmi_progress': 'Weight and BMI Progress',
        'positive': 'Positive Feedback',
        'weight_data': 'Weight Data',
        'weight_progress': 'Weight Progress',
        'no_weight_data': 'No weight data available',
        'bmi_progress': 'BMI Progress',
        'no_bmi_data': 'No BMI data available',
        'pyramid': 'Nutrition Pyramid',
        'body_positivity_quotes': 'Body Positivity Quotes'
    }
}
