# language.py

languages = {
    'Deutsch': {
        'welcome': "Willkommen",
        'login_register': "Login/Registrierung",
        'login': "Login",
        'register': "Registrierung",
        'forgot_password': "Passwort vergessen",
        'bmi_nutrition': "BMI & Ernährung",
        'track_meals_sports': "Mahlzeiten & Sport",
        'ki_features': "KI-Funktionalitäten",
        'db_management': "Datenbank-Verwaltung",
        'ekg_data': "EKG-Daten",
        'select_person': "Versuchsperson auswählen",
        'bmi_calculate': "BMI berechnen",
        'weight': "Gewicht (in kg)",
        'height': "Größe (in cm)",
        'gender': "Geschlecht",
        'male': "Männlich",
        'female': "Weiblich",
        'bmi_is': "Ihr BMI ist: {:.2f}",
        'bmi_status': "Sie befinden sich im Bereich: {}",
        'valid_height': "Bitte geben Sie eine gültige Größe ein.",
        'daily_calorie': "Täglicher Kalorienbedarf",
        'age': "Alter",
        'activity_level': "Aktivitätslevel",
        'activity_levels': ["Wenig aktiv", "Mäßig aktiv", "Aktiv", "Sehr aktiv"],
        'calorie_need': "Ihr täglicher Kalorienbedarf ist: {:.0f} kcal",
        'save_data': "Daten speichern",
        'success_save': "Daten erfolgreich gespeichert!",
        'weight_bmi_progress': "Gewichts- & BMI-Verlauf",
        'positive': "be Positive",
        'pyramid': "Ernährungspyramide",
        'body_positivity_quotes': "Zitate für Body Positivity",
        'no_data': "Keine Daten vorhanden. Andere Person wählen!",
        'select_meal_date': "Datum auswählen für Mahlzeiten",
        'no_meals': "Keine Mahlzeiten für das ausgewählte Datum gefunden.",
        'select_workout_date': "Datum auswählen für Sportaktivitäten",
        'no_workouts': "Keine Sportaktivitäten für das ausgewählte Datum gefunden.",
        'user_management': "Benutzerverwaltung",
        'show_user': "Benutzer anzeigen",
        'clean_data': "Datenbereinigung",
        'delete_all_data': "Alle Daten löschen",
        'confirm': "Bestätigen",
        'export_data': "Daten exportieren",
        'export_success': "Daten wurden exportiert",
        'backup_restore': "Datenbank-Backup und Wiederherstellung",
        'create_backup': "Backup erstellen",
        'backup_success': "Backup wurde erstellt",
        'upload_backup': "Backup-Datei hochladen",
        'restore_success': "Backup wurde wiederhergestellt",
        'data': "Daten",
        'graph': "Grafik",
        'average_heart_rate': "Durchschnittliche Herzfrequenz",
        'weight_data': "Gewichtsdaten",
        'weight_progress': "Gewichtsverlauf",
        'no_weight_data': "Keine Gewichtsdaten verfügbar",
        'bmi_progress': "BMI-Verlauf",
        'no_bmi_data': "Keine BMI-Daten verfügbar",
        'ki_description': "Hier werden KI-Funktionalitäten implementiert.",
        'user_not_found': "Benutzer nicht gefunden",
        'success_delete': "Alle Daten wurden gelöscht"
    },
    'English': {
        'welcome': "Welcome",
        'login_register': "Login/Registration",
        'login': "Login",
        'register': "Register",
        'forgot_password': "Forgot Password",
        'bmi_nutrition': "BMI & Nutrition",
        'track_meals_sports': "Track Meals & Sports",
        'ki_features': "AI Features",
        'db_management': "Database Management",
        'ekg_data': "EKG Data",
        'select_person': "Select Test Person",
        'bmi_calculate': "Calculate BMI",
        'weight': "Weight (in kg)",
        'height': "Height (in cm)",
        'gender': "Gender",
        'male': "Male",
        'female': "Female",
        'bmi_is': "Your BMI is: {:.2f}",
        'bmi_status': "You are in the range: {}",
        'valid_height': "Please enter a valid height.",
        'daily_calorie': "Daily Calorie Requirement",
        'age': "Age",
        'activity_level': "Activity Level",
        'activity_levels': ["Not very active", "Moderately active", "Active", "Very active"],
        'calorie_need': "Your daily calorie requirement is: {:.0f} kcal",
        'save_data': "Save Data",
        'success_save': "Data saved successfully!",
        'weight_bmi_progress': "Weight & BMI Progress",
        'positive': "Be Positive",
        'pyramid': "Nutrition Pyramid",
        'body_positivity_quotes': "Body Positivity Quotes",
        'no_data': "No data available. Select another person!",
        'select_meal_date': "Select Date for Meals",
        'no_meals': "No meals found for the selected date.",
        'select_workout_date': "Select Date for Workouts",
        'no_workouts': "No workouts found for the selected date.",
        'user_management': "User Management",
        'show_user': "Show User",
        'clean_data': "Clean Data",
        'delete_all_data': "Delete All Data",
        'confirm': "Confirm",
        'export_data': "Export Data",
        'export_success': "Data exported successfully",
        'backup_restore': "Database Backup and Restore",
        'create_backup': "Create Backup",
        'backup_success': "Backup created successfully",
        'upload_backup': "Upload Backup File",
        'restore_success': "Backup restored successfully",
        'data': "Data",
        'graph': "Graph",
        'average_heart_rate': "Average Heart Rate",
        'weight_data': "Weight Data",
        'weight_progress': "Weight Progress",
        'no_weight_data': "No weight data available",
        'bmi_progress': "BMI Progress",
        'no_bmi_data': "No BMI data available",
        'ki_description': "Here AI functionalities will be implemented.",
        'user_not_found': "User not found",
        'success_delete': "All data has been deleted"
    }
}
